// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDec9jFizbrTJFHBXImSRslKIpBhTGpPYg',
    appId: '1:314737080085:web:fa743e14688eb9887f5b1c',
    messagingSenderId: '314737080085',
    projectId: 'tiktok-clone-35aeb',
    authDomain: 'tiktok-clone-35aeb.firebaseapp.com',
    databaseURL: 'https://tiktok-clone-35aeb-default-rtdb.firebaseio.com',
    storageBucket: 'tiktok-clone-35aeb.appspot.com',
    measurementId: 'G-KQ9SB6GDGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy1Ww25f1-e7ySQ0c-U4pN0RMSH51ph58',
    appId: '1:314737080085:android:cdfcc92667f9d8d47f5b1c',
    messagingSenderId: '314737080085',
    projectId: 'tiktok-clone-35aeb',
    databaseURL: 'https://tiktok-clone-35aeb-default-rtdb.firebaseio.com',
    storageBucket: 'tiktok-clone-35aeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFKtbrlqw3UoopPg1fN6Ete4Lz9Nz5uL4',
    appId: '1:314737080085:ios:3223572b6241215c7f5b1c',
    messagingSenderId: '314737080085',
    projectId: 'tiktok-clone-35aeb',
    databaseURL: 'https://tiktok-clone-35aeb-default-rtdb.firebaseio.com',
    storageBucket: 'tiktok-clone-35aeb.appspot.com',
    androidClientId: '314737080085-lseefari0rp8t5o22bhspq9mc57luvoc.apps.googleusercontent.com',
    iosClientId: '314737080085-t1revsjs13a5q2ol3pd91vjbvoq2c35k.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
